#!/usr/bin/env python3
"""
Extract netlist information from VTR traditional run outputs.

This script parses the .net file generated by VTR and extracts:
1. Net counts for each DSP and BRAM block
2. Netlist graph structure with CLBs and connectivity
3. Statistics and summaries

Usage:
    python extract_netlist_info.py --benchmark diffeq1
    python extract_netlist_info.py --benchmark conv_layer --include-graph
    python extract_netlist_info.py --benchmark all
"""

import argparse
import sys
from pathlib import Path

from src.netlist.analyzer import (
    analyze_netlist,
    build_netlist_graph,
    save_net_count_json,
    save_netlist_graph_json,
)

PROJECT_ROOT = Path(__file__).resolve().parent


def extract_benchmark(benchmark_name: str, include_graph: bool = False) -> bool:
    """
    Extract netlist info for a single benchmark.

    Returns True if successful, False otherwise.
    """
    net_file = PROJECT_ROOT / "runs" / f"{benchmark_name}_traditional" / f"{benchmark_name}.net"

    if not net_file.exists():
        print(f"  [SKIP] No traditional run found at {net_file}")
        return False

    try:
        # Analyze netlist
        print(f"  Analyzing {net_file}...")
        stats = analyze_netlist(benchmark_name, net_file)
        print(f"    {stats.summary()}")

        # Save net counts
        output_json = PROJECT_ROOT / f"{benchmark_name}_netlist_info.json"
        save_net_count_json(stats, output_json)
        print(f"    Saved net counts to {output_json}")

        # Optionally save graph
        if include_graph:
            graph = build_netlist_graph(benchmark_name, net_file, include_clbs=True)
            graph_json = PROJECT_ROOT / f"{benchmark_name}_netlist_graph.json"
            save_netlist_graph_json(graph, graph_json)
            print(f"    Saved netlist graph to {graph_json}")
            print(f"    Graph: {graph.num_nodes()} nodes, {graph.num_edges()} edges")

        return True

    except Exception as e:
        print(f"  [ERROR] Failed to process {benchmark_name}: {e}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Extract netlist information from VTR traditional run outputs"
    )
    parser.add_argument(
        "--benchmark",
        type=str,
        default="diffeq1",
        help="Benchmark name (or 'all' to process all available). Default: diffeq1",
    )
    parser.add_argument(
        "--include-graph",
        action="store_true",
        help="Also generate netlist graph JSON files",
    )
    parser.add_argument(
        "--runs-dir",
        type=Path,
        default=PROJECT_ROOT / "runs",
        help="Root directory containing traditional run folders",
    )

    args = parser.parse_args()

    benchmarks_to_process = []

    if args.benchmark.lower() == "all":
        # Find all *_traditional folders
        for run_dir in args.runs_dir.iterdir():
            if run_dir.is_dir() and run_dir.name.endswith("_traditional"):
                bench_name = run_dir.name.replace("_traditional", "")
                benchmarks_to_process.append(bench_name)
        benchmarks_to_process.sort()
    else:
        benchmarks_to_process = [args.benchmark]

    if not benchmarks_to_process:
        print(f"No benchmarks found in {args.runs_dir}")
        sys.exit(1)

    print(f"Extracting netlist info for: {', '.join(benchmarks_to_process)}")
    print()

    successful = 0
    for benchmark in benchmarks_to_process:
        print(f"Processing {benchmark}...")
        if extract_benchmark(benchmark, include_graph=args.include_graph):
            successful += 1
        print()

    print(f"✓ Successfully extracted {successful}/{len(benchmarks_to_process)} benchmarks")

    if successful == len(benchmarks_to_process):
        sys.exit(0)
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
